### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by ht512512** [publicclass/express-partials#39]
Could not find any useful information or example to use the module. Even the basic questions like how to structure layout.ejs and index.ejs or how to use different layouts is missing. I for one, do not know how to use this module (and I do need it :( or will have to roll my own).

Any help?
- Hemant

**Comment by slaskis** [comment]
Right, I never added this because it's mostly meant for projects transitioning from express 2 to express 3 and this was an attempt to be the bridge.

But you're right, I should probably add a little example app, in the mean time you can look at the [express 2 ejs example](https://github.com/visionmedia/express/tree/2.x/examples/ejs) which uses layout and a partial.
