### ISSUE TITLE
Need tests for partial lookup

### ISSUE THREAD

**Issue by slaskis** [publicclass/express-partials#9]
A failing example, courtesy of @peters in issue #8:

> path to view that tries to render a partial: ./views/test/promo/main
> 
> <%- partial("test/promo/sub") %>
> 
> resolves to -> ./views/sub 
> should be -> ./views/test/promo/sub

**Comment by jeromegn** [comment]
+1

**Comment by zzen** [comment]
Just noticed the partial lookup and layout lookup share the same problem, so this is related to #11. I hope to do a fix today.

**Comment by slaskis** [comment]
@zzen that would be fantastic, I'm not too active right now as I don't use it at the moment, but I'll gladly put up a new version if you send me a PR.

**Comment by zzen** [comment]
@slaskis - I've got this fixed for layout file resolving, but I'm scrambling to find, within the `partial()` function, a place where I can read out from which template file it was called (since the partial lookups need to be relative to the current template file). Any ideas?

https://github.com/publicclass/express-partials/blob/master/index.js#L217
